[build]
command = "wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.550/quarto-1.4.550-linux-amd64.deb && dpkg -i quarto-1.4.550-linux-amd64.deb && quarto render"
publish = "_site"