[build]
command = "wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.550/quarto-1.4.550-linux-amd64.deb && sudo dpkg -i quarto-1.4.550-linux-amd64.deb && quarto render"
publish = "_site"

# Bagian [build.environment] di bawah ini tidak lagi wajib, jadi bisa Anda hapus
# atau biarkan saja. Perintah di atas yang akan dieksekusi.
[build.environment]
QUARTO_VERSION = "1.4.550"