[build]
command = "quarto render"
publish = "_site"

[build.environment]
# Dua baris ini memberitahu Netlify untuk menginstal Quarto dan R
# sebelum menjalankan perintah 'command'.
QUARTO_VERSION = "1.4.550"
R_VERSION = "4.3.2"